### ISSUE TITLE
我觉得，华为不会把他发布到github上

### ISSUE THREAD

**Issue by tangzejin921** [huawei-iot/HarmonyOS#8]
你个大骗子，来至杭州的骗子，还长期活跃在Flutter某个群里

**Comment by hantmac** [comment]
什么情况，这不是官方的repo吗

**Comment by tangzejin921** [comment]
是个吊，你看看作者就知道了，还有个一个fork都2百多了，估计也是假的

**Comment by snowwolfjay** [comment]
自慰。。。为什么不发？阿里巴巴的alios都发这里的

**Comment by Krocsky** [comment]
HormonyOS or HarmonyOS? 不说别的, 错别字都没法看.

**Comment by hantmac** [comment]
如果不是官方repo，还是不要用华为的图标了

**Comment by snowwolfjay** [comment]
> HormonyOS or HarmonyOS? 不说别的, 错别字都没法看.

你自创了Hormony?

**Comment by Krocsky** [comment]
> > HormonyOS or HarmonyOS? 不说别的, 错别字都没法看.
> 
> 你自创了Hormony?

说了错别字, 他文档里写的, 你有什么问题? 汉字看不懂咋的
